//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace QMP.Domain.Core
{
    public class Fact
    {

        public Dimension Dimension
        {
            get
            {
                throw new System.NotImplementedException();
            }
            set
            {
            }
        }

        public string Name
        {
            get
            {
                throw new System.NotImplementedException();
            }
            set
            {
            }
        }

        public string Value
        {
            get
            {
                throw new System.NotImplementedException();
            }
            set
            {
            }
        }
        public ValueType ValueType
        {
            get
            {
                throw new System.NotImplementedException();
            }
            set
            {
            }
        }
    }

}